Repository bit-team/backintime, pull requests merged in 2024-04, with the labels that each got.

#1700 doc(README): Remove known problem about "apt-key keyring" / Copyright adjustments
  CONTRIBUTING.md
  FAQ.md
  README.md
Labels: PR: Merge after creative-break

#1703 fix(diagnostics): OS name without further release files
  common/backintime.py
  common/diagnostics.py
Labels: PR: Waiting for review

#1696 Refactor: Replace Config.user() by getpass.getuser()
  CHANGES
  common/config.py
  common/mount.py
  common/snapshots.py
  common/test/test_backintime.py
  common/test/test_config.py
  common/test/test_sshtools.py
  qt/settingsdialog.py
Labels: PR: Merge after creative-break

#1695 fix(LogViewDialog): Remove Exclude, Copy and Decode context menu
  CHANGES
  qt/logviewdialog.py
Labels: PR: Merge after creative-break

#1688 Implement SSH Proxy Host
  CHANGES
  common/config.py
  common/snapshots.py
  common/sshtools.py
  common/test/test_sshtools.py
  qt/qttools.py
  qt/settingsdialog.py
Labels: Bug, PR: Waiting for review
