Repository bit-team/backintime, pull requests merged in 2024-05, with the labels that each got.

#1698 refactor!: Remove tools.syncfs()
  common/test/test_tools.py
  common/tools.py
Labels: PR: Merge after creative-break

#1702 Replace wrapLines() with Python's textwrap.wrap() #1699
  common/logger.py
  qt/qtsystrayicon.py
Labels: PR: Merge after creative-break

#1709 refactor!: Remove "filesystem_mounts" and "snapshot_version" field in backup "info" file
  CHANGES
  common/snapshots.py
  common/test/test_backintime.py
  common/test/test_snapshots.py
  common/test/test_tools.py
  common/tools.py
Labels: PR: Merge after creative-break

#1710 fix(gui): Improved Exclude tab in Manage profiles dialog with SSH encrypted profiles
  qt/settingsdialog.py
Labels: Cosmetics, PR: Merge after creative-break

#1717 doc: FAQ entry about Qt segmentation fault
  FAQ.md
  README.md
Labels: PR: Merge after creative-break

#1681 feat: Debug output for scheduled jobs (--debug in crontab)
  CHANGES
  FAQ.md
  common/config.py
  common/snapshots.py
  common/test/test_crontab.py
  common/test/test_diagnostics.py
  common/test/test_lint.py
  common/test/test_tools.py
  common/tools.py
  qt/app.py
  qt/plugins/systrayiconplugin.py
  qt/qttools_path.py
  qt/restoredialog.py
  qt/settingsdialog.py
  qt/test/test_lint.py
Labels: PR: Merge after creative-break

#1714 fix: "Backup folders" list should reflect the selected snapshot
  CHANGES
  qt/app.py
Labels: PR: Merge after creative-break

#1697 fix: Global flock file accessible by every user / Introducing FlockContext manager
  .codespellrc
  CHANGES
  common/applicationinstance.py
  common/doc-dev/flock.rst
  common/doc-dev/modules.rst
  common/flock.py
  common/snapshots.py
  common/test/test_backintime.py
  common/test/test_snapshots.py
  qt/settingsdialog.py
Labels: PR: Merge after creative-break

#1713 Tooltips
  .codespellrc
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  FAQ.md
  README.md
  qt/app.py
  qt/languagedialog.py
  qt/settingsdialog.py
Labels: PR: Merge after creative-break

#1712 fix(gui): Rephrase restore-config message dialog
  qt/app.py
  qt/settingsdialog.py
Labels: Qt, Cosmetics, PR: Merge after creative-break

#1725 feat: Update translations (2024-05-20)
  .codespellrc
  TRANSLATIONS
  common/languages.py
  common/po/ar.po
  common/po/bg.po
  common/po/bs.po
  common/po/ca.po
  common/po/cs.po
  common/po/da.po
  common/po/de.po
  common/po/el.po
  common/po/eo.po
  common/po/es.po
  common/po/et.po
  common/po/eu.po
  common/po/fa.po
  common/po/fi.po
  common/po/fo.po
  common/po/fr.po
  common/po/gl.po
  common/po/he.po
  common/po/hr.po
  common/po/hu.po
  common/po/id.po
  common/po/is.po
  common/po/it.po
  common/po/ja.po
  common/po/ko.po
  common/po/lt.po
  common/po/messages.pot
  common/po/nb.po
  common/po/nl.po
  common/po/nn.po
  common/po/pl.po
  common/po/pt.po
  common/po/pt_BR.po
  common/po/ro.po
  common/po/ru.po
  common/po/sk.po
  common/po/sl.po
  common/po/sr.po
  common/po/sv.po
  common/po/th.po
  common/po/tr.po
  common/po/uk.po
  common/po/vi.po
  common/po/zh_CN.po
  common/po/zh_TW.po
  qt/app.py
  qt/qtsystrayicon.py
  qt/settingsdialog.py
  qt/snapshotsdialog.py
Labels: High, PR: Merge after creative-break

#1689 Replace isipv6 method with builtin package
  common/test/test_tools.py
  common/tools.py
Labels: PR: Merge after creative-break
