Repository bit-team/backintime, pull requests merged in 2024-08, with the labels that each got.

#1829 [1.5.2] Fix: ValueError related to corrupt translations (Basque, Islandic, Spanish)
  CHANGES
  common/languages.py
  common/po/ar.po
  common/po/bs.po
  common/po/eo.po
  common/po/es.po
  common/po/et.po
  common/po/eu.po
  common/po/fa.po
  common/po/fo.po
  common/po/he.po
  common/po/is.po
  common/po/messages.pot
  common/po/uk.po
  common/po/vi.po
  common/po/zh_TW.po
  update_language_files.py
Labels: PR: Merge after creative-break

#1827 [1.5.2] fix: Crontab end with newline
  CHANGES
  common/schedule.py
Labels: PR: Merge after creative-break

#1833 chore: Start of new dev version v1.5.3-dev
  .travis.yml
  CHANGES
  VERSION
  common/doc-dev/BiT_release_process.md
  common/man/C/backintime-askpass.1
  common/man/C/backintime-config.1
  common/man/C/backintime.1
  common/version.py
  qt/man/C/backintime-qt.1
Labels: High

#1775 fix(lint): W0611 (unused imports)
  common/config.py
  common/doc-dev/conf.py
  common/encfstools.py
  common/password.py
  common/qt_probing.py
  common/snapshots.py
  common/test/test_applicationinstance.py
  common/test/test_backup.py
  common/test/test_config.py
  common/test/test_lint.py
  common/test/test_plugin_usercallback.py
  common/test/test_restore.py
  common/test/test_sid.py
  common/test/test_snapshotlog.py
  common/test/test_snapshots.py
  common/test/test_takeSnapshot.py
  common/test/test_tools.py
  common/tools.py
Labels: PR: Merge after creative-break

#1816 build!: Minimum Python version 3.9 required
  .travis.yml
  CHANGES
  CONTRIBUTING.md
  common/configure
  qt/configure
Labels: PR: Merge after creative-break

#1810 chore: Remove Coveralls
  .travis.yml
  README.md
  common/.coveragerc
  common/configure
  qt/configure
Labels: PR: Merge after creative-break

#1825 chore: Improve behavior on skipping tests
  common/test/generic.py
  common/test/test_backintime.py
  common/test/test_snapshots.py
  common/test/test_sshtools.py
  common/tools.py
Labels: PR: Merge after creative-break

#1800 fix: Prevent duplicates in Exclude/Include list of Manage Profiles dialog
  qt/icon.py
  qt/settingsdialog.py
Labels: Cosmetics, PR: Merge after creative-break, Code Quality

#1801 refactor!: Remove OrderedSet without replacement
  CHANGES
  common/snapshots.py
  common/test/test_snapshots.py
  common/tools.py
Labels: PR: Merge after creative-break

#1794 Enable lint rule W0237 (needs heavy refactoring)
  common/applicationinstance.py
  common/guiapplicationinstance.py
  common/test/test_lint.py
  common/tools.py
Labels: PR: Merge after creative-break, Code Quality

#1832 fix(gui): Fix Qt segmentation fault when canceling out of unconfigured BiT (#1095)
  CHANGES
  qt/app.py
Labels: PR: Merge after creative-break

#1837 doc: Manual tests and installing
  CHANGES
  CONTRIBUTING.md
  common/doc-dev/BiT_release_process.md
Labels: PR: Merge after creative-break

#1835 Fix: Correct global flock fallbacks (#1834)
  CHANGES
  common/flock.py
Labels: High, Bug, PR: Waiting for review, PR: Merge after creative-break

#1790 Worked on fixing issue W0612 (unused-variable) in "common"
  common/config.py
  common/schedule.py
  common/sshtools.py
  common/test/test_applicationinstance.py
  common/test/test_lint.py
  common/test/test_plugin_usercallback.py
  common/tools.py
  qt/test/test_lint.py
Labels: PR: Merge after creative-break

#1814 chore: Show process id in debug messages (#1792)
  CHANGES
  common/config.py
  common/logger.py
  common/test/test_tools.py
  common/tools.py
Labels: PR: Modifications requested

#1842 refactor: "General" tab and its "Schedule" section
  CHANGES
  qt/combobox.py
  qt/encfsmsgbox.py
  qt/schedulewidget.py
  qt/settingsdialog.py
Labels: PR: Merge after creative-break

#1846 fix(doc): backintime-config man page
  common/config.py
  common/doc-dev/BiT_release_process.md
  common/man/C/backintime-config.1
  create-manpage-backintime-config.py
Labels: PR: Merge after creative-break

#1848 chore: Logging around canBackup function
  common/backintime.py
  common/config.py
  common/snapshots.py
Labels: PR: Merge after creative-break

#1803 refactoring: enable pylint checks for R0801
  common/encfstools.py
  common/mount.py
  common/test/constants.py
  common/test/test_applicationinstance.py
  common/test/test_config_crontab.py
  common/test/test_lint.py
  common/test/test_plugin_usercallback.py
  common/test/test_restore.py
  common/test/test_snapshots.py
  common/test/test_tools.py
  qt/app.py
  qt/logviewdialog.py
  qt/qtsystrayicon.py
  qt/qttools.py
  qt/settingsdialog.py
  qt/test/test_lint.py
Labels: PR: Modifications requested

#1840 chore: Fix appstream meta data & clarify license as "GPL-2.0-or-later"
  qt/io.github.bit_team.back_in_time.gui.metainfo.xml
Labels: Discussion, PR: Merge after creative-break

#1841 refactor: Daemon class clarify its license
  CONTRIBUTING.md
  common/cli.py
  common/daemon.py
  common/flock.py
  common/password.py
  common/tools.py
Labels: Discussion, PR: Merge after creative-break

#1839 Support ed25519 SSH keys for SSH tests
  CONTRIBUTING.md
  common/doc-dev/3_How_to_set_up_openssh_server_for_ssh_unit_tests.md
  common/test/generic.py
  common/test/test_sshtools.py
Labels: Discussion, PR: Merge after creative-break
