Repository bit-team/backintime, pull requests merged in 2024-07, with the labels that each got.

#1777 Update TRANSLATIONS
  TRANSLATIONS
Labels: PR: Merge after creative-break

#1776 Fix typo in mount.py error message
  common/mount.py
Labels: PR: Merge after creative-break

#1778 fix(translation): Minor improvements of source strings
  common/config.py
  qt/app.py
  qt/qttools.py
  qt/settingsdialog.py
  qt/snapshotsdialog.py
Labels: PR: Merge after creative-break

#1733 build: Remove debian folder
  CHANGES
  debian/backintime-qt.maintscript
  debian/changelog
  debian/compat
  debian/control
  debian/copyright
  debian/rules
  debian/source/format
  makedeb-src.sh
  makedeb.sh
Labels: Infrastructure, PR: Waiting for review

#1774 doc(FAQ): What happens when I remove a snapshot (#875)
  FAQ.md
Labels: PR: Merge after creative-break

#1756 fix: Global flock fallback to single-user mode if not enough permissions
  CHANGES
  TRANSLATIONS
  common/doc-dev/conf.py
  common/flock.py
  common/snapshots.py
  common/tools.py
Labels: PR: Waiting for review, PR: Merge after creative-break

#1783 Fix/1755 Enable lint checks that already pass successfully
  common/test/test_lint.py
Labels: PR: Merge after creative-break

#1782 chore: Clean update-version script from "debian" folder
  updatecopyright.sh
  updateversion.sh
Labels: High, Bug, PR: Waiting for review, PR: Merge after creative-break

#1787 fix(build): Remove debian/copyright from configure script (#1548)
  common/configure
  qt/configure
Labels: High, Infrastructure, Bug, PR: Merge after creative-break

#1789 Enable lint checks W0123 and W0707
  common/mount.py
  common/test/test_lint.py
  common/test/test_plugin_usercallback.py
  common/tools.py
Labels: PR: Merge after creative-break

#1804 doc(CONTRIBUTION): Single quotes and black
  CONTRIBUTING.md
Labels: PR: Merge after creative-break

#1802 Update Arabic TRANSLATIONS
  TRANSLATIONS
Labels: PR: Merge after creative-break

#1797 Update FAQ.md: Segfault-on-Exit bug fixed
  FAQ.md
Labels: PR: Merge after creative-break

#1786 Create HISTORY.md
  HISTORY.md
Labels: PR: Merge after creative-break

#1805 chore(translation): Update
  .travis.yml
  TRANSLATIONS
  common/languages.py
  common/po/ar.po
  common/po/bg.po
  common/po/bs.po
  common/po/ca.po
  common/po/cs.po
  common/po/da.po
  common/po/de.po
  common/po/el.po
  common/po/eo.po
  common/po/es.po
  common/po/et.po
  common/po/eu.po
  common/po/fa.po
  common/po/fi.po
  common/po/fo.po
  common/po/fr.po
  common/po/gl.po
  common/po/he.po
  common/po/hr.po
  common/po/hu.po
  common/po/id.po
  common/po/is.po
  common/po/it.po
  common/po/ja.po
  common/po/ko.po
  common/po/lt.po
  common/po/messages.pot
  common/po/nb.po
  common/po/nl.po
  common/po/nn.po
  common/po/pl.po
  common/po/pt.po
  common/po/pt_BR.po
  common/po/ro.po
  common/po/ru.po
  common/po/sk.po
  common/po/sl.po
  common/po/sr.po
  common/po/sv.po
  common/po/th.po
  common/po/tr.po
  common/po/uk.po
  common/po/vi.po
  common/po/zh_CN.po
  common/po/zh_TW.po
Labels: PR: Merge after creative-break

#1806 Release Candidate: Back in Time 1.5.0
  CHANGES
  README.md
  TRANSLATIONS
  VERSION
  common/bitbase.py
  common/doc-dev/BiT_release_process.md
  common/man/C/backintime-askpass.1
  common/man/C/backintime-config.1
  common/man/C/backintime.1
  common/version.py
  qt/man/C/backintime-qt.1
Labels: PR: Merge after creative-break

#1817 fix: Ping SSH proxy use correct port (#1815)
  CHANGES
  common/sshtools.py
  qt/settingsdialog.py
Labels: High, Bug, PR: Waiting for review, PR: Merge after creative-break
