Repository bit-team/backintime, pull requests merged in 2024-06, with the labels that each got.

#1730 fix: Weekdays and months correct translated (and fix TravisCI config)
  .travis.yml
  CHANGES
  common/doc-dev/1_doc_maintenance_howto.md
  common/doc-dev/conf.py
  common/doc-dev/index.rst
  common/tools.py
  qt/qttools.py
  qt/settingsdialog.py
Labels: Cosmetics, PR: Merge after creative-break

#1739 doc(FAQ): How to read logs
  FAQ.md
Labels: Documentation, PR: Merge after creative-break

#1740 fix(gui): SSHProxyWidget handle port values of type integer
  qt/settingsdialog.py
Labels: Bug, PR: Merge after creative-break

#1732 translation: Improve BIDI/RTF support and minor mods
  FAQ.md
  README.md
  common/backintime.py
  common/config.py
  common/diagnostics.py
  common/doc-dev/2_localization.md
  common/encfstools.py
  common/mount.py
  common/password.py
  common/snapshots.py
  common/sshtools.py
  qt/app.py
  qt/logviewdialog.py
  qt/messagebox.py
  qt/qtsystrayicon.py
  qt/settingsdialog.py
  qt/snapshotsdialog.py
  update_language_files.py
Labels: PR: Merge after creative-break

#1746 ci: Remove ppc64le architecture
  .travis.yml
  common/test/test_lint.py
  qt/serviceHelper.py
  qt/test/test_lint.py
Labels: PR: Merge after creative-break

#1749 translation: Update translation
  common/languages.py
  common/po/ar.po
  common/po/bg.po
  common/po/bs.po
  common/po/ca.po
  common/po/cs.po
  common/po/da.po
  common/po/de.po
  common/po/el.po
  common/po/eo.po
  common/po/es.po
  common/po/et.po
  common/po/eu.po
  common/po/fa.po
  common/po/fi.po
  common/po/fo.po
  common/po/fr.po
  common/po/gl.po
  common/po/he.po
  common/po/hr.po
  common/po/hu.po
  common/po/id.po
  common/po/is.po
  common/po/it.po
  common/po/ja.po
  common/po/ko.po
  common/po/lt.po
  common/po/messages.pot
  common/po/nb.po
  common/po/nl.po
  common/po/nn.po
  common/po/pl.po
  common/po/pt.po
  common/po/pt_BR.po
  common/po/ro.po
  common/po/ru.po
  common/po/sk.po
  common/po/sl.po
  common/po/sr.po
  common/po/sv.po
  common/po/th.po
  common/po/tr.po
  common/po/uk.po
  common/po/vi.po
  common/po/zh_CN.po
  common/po/zh_TW.po
  update_language_files.py
Labels: High

#1748 refactor!: Remove test about sshkeygen (only running on Germar's machine)
  CHANGES
  common/test/test_lint.py
  common/test/test_sshtools.py
  qt/test/test_lint.py
Labels: PR: Merge after creative-break

#1747 refactor: Extract and decouple cron-related code from config.py and tools.py
  .codespellrc
  common/cli.py
  common/config.py
  common/configfile.py
  common/doc-dev/modules.rst
  common/doc-dev/schedule.rst
  common/schedule.py
  common/snapshots.py
  common/test/test_config.py
  common/test/test_config_crontab.py
  common/test/test_schedule.py
  common/test/test_tools.py
  common/tools.py
  qt/settingsdialog.py
Labels: PR: Merge after creative-break

#1758 refactor: Activate and fix PyLint rule W0311 (bad indentation)
  CHANGES
  CONTRIBUTING.md
  TRANSLATIONS
  common/encfstools.py
  common/test/test_lint.py
  qt/test/test_lint.py
Labels: PR: Merge after creative-break

#1759 refactor: Enable and fix PyLint rule C0303 (trailing-whitespaces)
  CHANGES
  common/test/test_lint.py
  common/tools.py
  qt/test/test_lint.py
Labels: PR: Merge after creative-break

#1761 feat: Warn if cron is not running
  .travis.yml
  CHANGES
  common/config.py
  common/doc-dev/BiT_release_process.md
  common/schedule.py
  common/test/test_lint.py
  qt/test/test_lint.py
Labels: PR: Merge after creative-break

#1762 Only show directories in places window #1760
  qt/app.py
Labels: PR: Merge after creative-break

#1766 refactor: Enable and fix PyLint rules C0305 (trailing-newlines), C0324 (superfluous-parens), C0410 (multiple-imports), E0213 (no-self-argument)
  CHANGES
  common/cli.py
  common/mount.py
  common/password.py
  common/snapshots.py
  common/test/test_config_crontab.py
  common/test/test_lint.py
  common/test/test_snapshotlog.py
  common/tools.py
  qt/messagebox.py
  qt/qttools.py
  qt/qttools_path.py
  qt/test/test_lint.py
Labels: PR: Merge after creative-break

#1767 refactor!: Removed unused debug code and minor pylint fixes
  CHANGES
  TRANSLATIONS
  common/test/test_lint.py
  common/tools.py
  qt/app.py
  qt/settingsdialog.py
  qt/test/test_lint.py
Labels: PR: Merge after creative-break

#1768 fix(gui): remove ExtraMouseButtonEventFilter when closing (#1095)
  CHANGES
  qt/app.py
Labels: PR: Merge after creative-break

#1770 feat(gui): Use flag-like icon for language menu entries
  qt/app.py
  qt/icon.py
Labels: Cosmetics, PR: Merge after creative-break
